### ISSUE TITLE
Invalid server token, relog to fix 

### ISSUE THREAD

**Issue by StevenCrazyFire** [kuroppoi/brainwine#14]
Idk why but I tried updating the thing by just reinstalling deepworld and putting brainwine again from scratch and nothing still worked

Also I just learning GitHub so sorry for posting multiple times

**Comment by kuroppoi** [comment]
Getting stuck being unable to log in nor log out typically happens when you close the game before registering your account and then switching servers. If you no longer have access to the server containing your unregistered account, I have updated the Windows patching kit to include a .reg file that clears all settings and forces a logout. Hope this helps!

**Comment by StevenCrazyFire** [comment]
It worked, thanks for the fix and thanks for letting us relive our nostalgia with you rebuilding deepworld 
I hope you finish this game and Make it the way it was before shutdown so we can play together again

**Comment by kuroppoi** [comment]
Glad the issue is resolved.
