### ISSUE TITLE
How to give yourself absolutely all the things in the game along with all the clothes?

### ISSUE THREAD

**Issue by Lanchochik228** [kuroppoi/brainwine#35]
I want to give myself all the things in the game, I know the command “all” But it only gives out Weapons, Blocks, Accessories, etc. But How can I give myself all the clothes in the game? It’s just very inconvenient to blow out the bottom of your clothes. Please tell me how to give myself all the clothes!(┬┬﹏┬┬)

**Comment by kuroppoi** [comment]
Commit b737d46b1d53260c86fd4d1d20aa8bb9745d965e (on the [develop branch](https://github.com/kuroppoi/brainwine/tree/develop)) has made it so that `/give <player> all` will now also give the target player every clothing item and emote in the game.

It hasn't been published as part of a release yet, so if you want to access this experimental feature along with others then you may download a recent build artifact from here:
https://github.com/kuroppoi/brainwine/actions?query=branch%3Adevelop

As of this comment, the most recent artifact may be downloaded from here:
https://github.com/kuroppoi/brainwine/actions/runs/8216554652/artifacts/1311953078

**Comment by Lanchochik228** [comment]
Thanks you Very Much!

**Comment by Lanchochik228** [comment]
https://github.com/kuroppoi/brainwine/assets/134071046/23929e71-c633-474d-b142-c39bec5b0997
